# Generated by Django 5.2.16 on 2026-07-15 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0014_alter_accessprofilecapability_organization_and_more'),
        ('webchat', '0002_websession_organization'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM webchat_websession session
                        JOIN integrations_integration connection ON connection.id = session.connection_id
                        JOIN conversations_connectionidentity identity ON identity.id = session.identity_id
                        JOIN conversations_contact contact ON contact.id = identity.contact_id
                        WHERE connection.organization_id <> contact.organization_id
                    ) THEN
                        RAISE EXCEPTION 'C04 preflight: cross-tenant web session exists';
                    END IF;
                END $$;

                UPDATE webchat_websession session
                SET organization_id = connection.organization_id
                FROM integrations_integration connection
                WHERE session.connection_id = connection.id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='websession',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
    ]
