# Generated by Django 5.2.16 on 2026-07-12 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('STAFF', 'Сотрудник'), ('CUSTOMER', 'Клиент')], max_length=16)),
                ('connection_type', models.CharField(choices=[('DIRECT', 'Прямое P2P'), ('RELAY', 'Через TURN relay'), ('UNKNOWN', 'Неизвестно')], default='UNKNOWN', max_length=16)),
                ('local_candidate_type', models.CharField(blank=True, max_length=8)),
                ('remote_candidate_type', models.CharField(blank=True, max_length=8)),
                ('round_trip_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='calls.callsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('call_session', 'side'), name='uniq_call_metric_side')],
            },
        ),
    ]
