# Generated by Django 5.2.16 on 2026-07-15 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_callinvite_organization_callmetric_organization_and_more'),
        ('identity', '0014_alter_accessprofilecapability_organization_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM calls_callinvite invite
                        JOIN calls_callsession call ON call.id = invite.call_session_id
                        JOIN conversations_connectionidentity identity ON identity.id = invite.connection_identity_id
                        JOIN conversations_contact contact ON contact.id = identity.contact_id
                        WHERE call.organization_id <> contact.organization_id
                    ) OR EXISTS (
                        SELECT 1
                        FROM calls_callparticipant participant
                        JOIN calls_callsession call ON call.id = participant.call_session_id
                        JOIN conversations_connectionidentity identity ON identity.id = participant.connection_identity_id
                        JOIN conversations_contact contact ON contact.id = identity.contact_id
                        WHERE participant.connection_identity_id IS NOT NULL
                          AND call.organization_id <> contact.organization_id
                    ) THEN
                        RAISE EXCEPTION 'C04 preflight: cross-tenant call relation exists';
                    END IF;
                END $$;

                UPDATE calls_callinvite invite
                SET organization_id = call.organization_id
                FROM calls_callsession call
                WHERE invite.call_session_id = call.id;

                UPDATE calls_callparticipant participant
                SET organization_id = call.organization_id
                FROM calls_callsession call
                WHERE participant.call_session_id = call.id;

                UPDATE calls_callmetric metric
                SET organization_id = call.organization_id
                FROM calls_callsession call
                WHERE metric.call_session_id = call.id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='callinvite',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
        migrations.AlterField(
            model_name='callmetric',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
        migrations.AlterField(
            model_name='callparticipant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
    ]
