# Generated by Django 5.2.15 on 2026-07-15 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0015_organization_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationProvisioning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('request_hash', models.CharField(max_length=128)),
                ('source', models.CharField(choices=[('PLATFORM_OPERATOR', 'Platform operator'), ('SELF_SERVICE', 'Self-service'), ('SELF_HOSTED_SETUP', 'Self-hosted setup'), ('MIGRATION', 'Migration')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('WAITING_FOR_OWNER', 'Waiting for owner'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=32)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('failure_details_safe', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provisioning_records', to='identity.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provisioning_requests', to='platform.platformoperator')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'updated_at'], name='platform_or_status_6fe68b_idx'), models.Index(fields=['source', 'created_at'], name='platform_or_source_93a140_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlatformToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='platform.platformoperator')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('token_hash__isnull', False), models.Q(('token_hash', ''), _negated=True)), name='platform_token_hash_present')],
            },
        ),
    ]
