# Generated by Django 5.2.15 on 2026-06-23 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_knowledgedocument_knowledgedocumentversion_and_more'),
        ('products', '0004_remove_price_uniq_price_offer_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAIRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Опубликован'), ('ARCHIVED', 'Архив')], default='DRAFT', max_length=16)),
                ('model', models.CharField(max_length=128)),
                ('model_params', models.JSONField(blank=True, default=dict)),
                ('allowed_tools', models.JSONField(blank=True, default=list)),
                ('limits', models.JSONField(blank=True, default=dict)),
                ('retrieval_index_version', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_releases', to='products.product')),
            ],
            options={
                'ordering': ['product_id', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseKnowledgeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ai.knowledgedocumentversion')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_versions', to='ai.productairelease')),
            ],
        ),
        migrations.CreateModel(
            name='ReleasePromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ai.promptdocumentversion')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_versions', to='ai.productairelease')),
            ],
        ),
        migrations.AddConstraint(
            model_name='productairelease',
            constraint=models.UniqueConstraint(fields=('product', 'version'), name='uniq_release_product_version'),
        ),
        migrations.AddConstraint(
            model_name='productairelease',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PUBLISHED')), fields=('product',), name='uniq_active_release_per_product'),
        ),
        migrations.AddConstraint(
            model_name='releaseknowledgeversion',
            constraint=models.UniqueConstraint(fields=('release', 'knowledge_version'), name='uniq_release_knowledge_version'),
        ),
        migrations.AddConstraint(
            model_name='releasepromptversion',
            constraint=models.UniqueConstraint(fields=('release', 'prompt_version'), name='uniq_release_prompt_version'),
        ),
    ]
