# Generated by Django 5.2.15 on 2026-06-23 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_productairelease_releaseknowledgeversion_and_more'),
        ('products', '0004_remove_price_uniq_price_offer_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmInvocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=64)),
                ('operation', models.CharField(max_length=16)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cost_micros', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('SUCCESS', 'Успех'), ('ERROR', 'Ошибка'), ('BLOCKED', 'Заблокировано лимитом')], default='SUCCESS', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_invocations', to='products.product')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invocations', to='ai.productairelease')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='ai_llminvoc_product_2936b3_idx')],
            },
        ),
    ]
