# Generated by Django 5.2.15 on 2026-06-24 16:40

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_llminvocation'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='llminvocation',
            name='used_fragment_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='KnowledgeFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='ai.knowledgedocumentversion')),
            ],
            options={
                'ordering': ['version_id', 'chunk_index'],
                'constraints': [models.UniqueConstraint(fields=('version', 'chunk_index'), name='uniq_fragment_version_chunk')],
            },
        ),
    ]
