# Generated by Django 5.2.15 on 2026-06-27 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_llminvocation_used_fragment_ids_knowledgefragment'),
        ('channels', '0002_channel_system_prompt'),
        ('products', '0005_remove_price_price_amount_positive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llminvocation',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_invocations', to='channels.channel'),
        ),
        migrations.AlterField(
            model_name='llminvocation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_invocations', to='products.product'),
        ),
    ]
