# Generated by Django 5.2.15 on 2026-09-03 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # Дроп после tenancy-гардов (RLS/триггеры ссылаются на эти таблицы).
        ('tenancy', '0017_drop_commerce'),
        ('ai', '0013_portal_article_knowledge'),
    ]

    operations = [
        # Constraint снимается до полей: иначе state хранит constraint на
        # несуществующее поле и обратный DeleteModel падает при create_model.
        migrations.RemoveConstraint(
            model_name='knowledgedepartment',
            name='uniq_knowledge_department',
        ),
        migrations.RemoveField(
            model_name='knowledgedepartment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='knowledgedepartment',
            name='knowledge',
        ),
        migrations.RemoveField(
            model_name='knowledgedepartment',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='knowledge',
            name='departments',
        ),
        migrations.RemoveConstraint(
            model_name='knowledge',
            name='knowledge_visibility_valid',
        ),
        migrations.RemoveField(
            model_name='knowledge',
            name='visibility',
        ),
        migrations.DeleteModel(
            name='KnowledgeDepartment',
        ),
    ]
