# Generated by Django 5.2.15 on 2026-07-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_conversation_support_identity_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionidentity',
            name='username',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='message',
            name='kind',
            field=models.CharField(blank=True, choices=[('', 'Текст'), ('contact_request', 'Запрос контакта'), ('contact', 'Контакт')], default='', max_length=32),
        ),
    ]
