# Generated by Django 5.2.16 on 2026-07-15 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_connectionidentity_organization_and_more'),
        ('identity', '0014_alter_accessprofilecapability_organization_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM conversations_connectionidentity identity
                        JOIN conversations_contact contact ON contact.id = identity.contact_id
                        JOIN integrations_integration connection ON connection.id = identity.connection_id
                        WHERE contact.organization_id <> connection.organization_id
                    ) THEN
                        RAISE EXCEPTION 'C04 preflight: cross-tenant connection identity exists';
                    END IF;
                END $$;

                UPDATE conversations_connectionidentity identity
                SET organization_id = contact.organization_id
                FROM conversations_contact contact
                WHERE identity.contact_id = contact.id;

                UPDATE conversations_conversationread read
                SET organization_id = conversation.organization_id
                FROM conversations_conversation conversation
                WHERE read.conversation_id = conversation.id;

                UPDATE conversations_message message
                SET organization_id = conversation.organization_id
                FROM conversations_conversation conversation
                WHERE message.conversation_id = conversation.id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='connectionidentity',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
        migrations.AlterField(
            model_name='conversationread',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
        migrations.AlterField(
            model_name='message',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
    ]
