# Generated by Django 5.2.15 on 2026-09-04 20:40

import hub_platform.conversations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0011_conversation_archived_at_conversation_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, max_length=512, upload_to=hub_platform.conversations.models.message_audio_upload_path),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_content_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='message',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='transcript',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='transcript_status',
            field=models.CharField(choices=[('NONE', 'Не расшифровано'), ('READY', 'Готова'), ('FAILED', 'Ошибка')], default='NONE', max_length=8),
        ),
        migrations.AlterField(
            model_name='message',
            name='kind',
            field=models.CharField(blank=True, choices=[('', 'Текст'), ('contact_request', 'Запрос контакта'), ('contact', 'Контакт'), ('voice', 'Голосовое сообщение')], default='', max_length=32),
        ),
    ]
