# Generated by Django 5.2.15 on 2026-07-08 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0002_channel_system_prompt'),
        ('identity', '0006_alter_employeeprofile_totp_secret'),
        ('products', '0006_product_ingest_token_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSupportContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64)),
                ('version', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('ACTIVE', 'Активен'), ('DEPRECATED', 'Устаревший'), ('DISABLED', 'Отключён')], default='DRAFT', max_length=16)),
                ('schema_json', models.JSONField(blank=True, default=dict)),
                ('identity_mapping_json', models.JSONField(blank=True, default=dict)),
                ('operator_ui_json', models.JSONField(blank=True, default=dict)),
                ('ai_context_json', models.JSONField(blank=True, default=dict)),
                ('search_mapping_json', models.JSONField(blank=True, default=dict)),
                ('sensitive_fields_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_channels', models.ManyToManyField(blank=True, related_name='allowed_support_contracts', to='channels.channel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_contracts', to='identity.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_contracts', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='SupportIdentitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_code', models.CharField(max_length=64)),
                ('subject_key', models.CharField(db_index=True, max_length=128)),
                ('account_key', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('display_email', models.CharField(blank=True, max_length=255)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('operator_context_json', models.JSONField(blank=True, default=dict)),
                ('ai_context_json', models.JSONField(blank=True, default=dict)),
                ('search_text', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('token_issued_at', models.DateTimeField()),
                ('token_expires_at', models.DateTimeField()),
                ('token_jti_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='support.productsupportcontract')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_identity_snapshots', to='identity.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_identity_snapshots', to='products.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='productsupportcontract',
            index=models.Index(fields=['product', 'status'], name='support_pro_product_962332_idx'),
        ),
        migrations.AddConstraint(
            model_name='productsupportcontract',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_support_contract_org_code'),
        ),
        migrations.AddIndex(
            model_name='supportidentitysnapshot',
            index=models.Index(fields=['product', 'subject_key'], name='support_sup_product_155363_idx'),
        ),
        migrations.AddIndex(
            model_name='supportidentitysnapshot',
            index=models.Index(fields=['product', 'account_key'], name='support_sup_product_ae9686_idx'),
        ),
    ]
