# Generated by Django 5.2.15 on 2026-07-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsupportcontract',
            name='code',
            field=models.CharField(max_length=64),
        ),
    ]
