# Generated by Django 5.2.15 on 2026-06-17 15:23

import django.utils.timezone
import hub_platform.identity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='humanuser',
            managers=[
                ('objects', hub_platform.identity.models.HumanUserManager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='identity_au_organiz_0cd628_idx',
            old_name='identity_au_organiz_6d3427_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='identity_au_action_9f9acf_idx',
            old_name='identity_au_action_14c78b_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='identity_au_object__06d2fb_idx',
            old_name='identity_au_object__0186bf_idx',
        ),
        migrations.AlterField(
            model_name='humanuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='humanuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='humanuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='humanuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='humanuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='humanuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
