# Generated by Django 5.2.15 on 2026-06-23 15:19

import hub_platform.identity.crypto
from django.db import migrations

_TABLE = "identity_employeeprofile"


def _encrypt_existing(apps, schema_editor):
    from hub_platform.identity.crypto import encrypt_secret

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"SELECT id, totp_secret FROM {_TABLE} WHERE totp_secret <> ''")
        rows = cursor.fetchall()
    for pk, secret in rows:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(f"UPDATE {_TABLE} SET totp_secret = %s WHERE id = %s", [encrypt_secret(secret), pk])


def _decrypt_existing(apps, schema_editor):
    from hub_platform.identity.crypto import decrypt_secret

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"SELECT id, totp_secret FROM {_TABLE} WHERE totp_secret <> ''")
        rows = cursor.fetchall()
    for pk, secret in rows:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(f"UPDATE {_TABLE} SET totp_secret = %s WHERE id = %s", [decrypt_secret(secret), pk])


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_move_product_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='totp_secret',
            field=hub_platform.identity.crypto.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.RunPython(_encrypt_existing, _decrypt_existing),
    ]
