# Generated by Django 5.2.15 on 2026-06-28 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0006_alter_employeeprofile_totp_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DIALOG_WAITING', 'Диалог ждёт оператора'), ('PAYMENT_RECEIVED', 'Платёж получен'), ('PAYMENT_FAILED', 'Проблема с платежом'), ('RELEASE_PUBLISHED', 'Опубликован релиз агента'), ('INTEGRATION_ERROR', 'Ошибка интеграции'), ('LIMIT_REACHED', 'Достигнут лимит')], max_length=32)),
                ('level', models.CharField(choices=[('INFO', 'Инфо'), ('SUCCESS', 'Успех'), ('WARNING', 'Предупреждение'), ('CRITICAL', 'Критично')], default='INFO', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('target_route', models.CharField(blank=True, max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('audience', models.CharField(choices=[('ALL', 'Все'), ('OWNER', 'Владелец'), ('OPERATORS', 'Операторы'), ('USER', 'Конкретный пользователь')], default='ALL', max_length=16)),
                ('source_type', models.CharField(blank=True, max_length=64)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('dedup_key', models.CharField(blank=True, db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='identity.organization')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', 'created_at'], name='notificatio_organiz_b709e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationread',
            constraint=models.UniqueConstraint(fields=('notification', 'user'), name='uniq_notification_read'),
        ),
    ]
