# Generated by Django 5.2.15 on 2026-06-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('DIALOG_WAITING', 'Диалог ждёт оператора'), ('DIALOG_NEW_MESSAGE', 'Новое сообщение в диалоге'), ('PAYMENT_RECEIVED', 'Платёж получен'), ('PAYMENT_FAILED', 'Проблема с платежом'), ('RELEASE_PUBLISHED', 'Опубликован релиз агента'), ('INTEGRATION_ERROR', 'Ошибка интеграции'), ('LIMIT_REACHED', 'Достигнут лимит')], max_length=32),
        ),
    ]
