# Generated by Django 5.2.16 on 2026-07-12 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0011_enforce_capability_registry'),
        ('notifications', '0003_messengerbindingcode_messengerbinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='identity.department'),
        ),
    ]
