# Generated by Django 5.2.16 on 2026-07-15 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0014_alter_accessprofilecapability_organization_and_more'),
        ('notifications', '0005_messengerbinding_organization_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                UPDATE notifications_messengerbinding binding
                SET organization_id = integration.organization_id
                FROM integrations_integration integration
                WHERE binding.integration_id = integration.id;

                UPDATE notifications_messengerbindingcode code
                SET organization_id = integration.organization_id
                FROM integrations_integration integration
                WHERE code.integration_id = integration.id;

                UPDATE notifications_notificationread read
                SET organization_id = notification.organization_id
                FROM notifications_notification notification
                WHERE read.notification_id = notification.id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='messengerbinding',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
        migrations.AlterField(
            model_name='messengerbindingcode',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
        migrations.AlterField(
            model_name='notificationread',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
    ]
