# Generated by Django 5.2.15 on 2026-09-03 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # Дроп после tenancy-гардов (RLS/триггеры ссылаются на эти таблицы).
        ('tenancy', '0017_drop_commerce'),
        ('notifications', '0007_drop_payment_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='department',
        ),
    ]
