# Generated by Django 5.2.17 on 2026-09-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='body_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='notification',
            name='text_params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
