# Generated by Django 5.2.16 on 2026-07-15 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_outbox_tenant_context'),
        ('identity', '0014_alter_accessprofilecapability_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxevent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbox_events', to='identity.organization'),
        ),
        migrations.AddField(
            model_name='inboxevent',
            name='ownership',
            field=models.CharField(choices=[('PLATFORM', 'Platform'), ('TENANT', 'Tenant')], db_index=True, default='PLATFORM', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='inboxevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', False), ('ownership', 'TENANT')), models.Q(('organization__isnull', True), ('ownership', 'PLATFORM')), _connector='OR'), name='inbox_ownership_matches_organization'),
        ),
        migrations.AddConstraint(
            model_name='outboxevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', False), ('ownership', 'TENANT')), models.Q(('organization__isnull', True), ('ownership', 'PLATFORM')), _connector='OR'), name='outbox_ownership_matches_organization'),
        ),
    ]
