# Generated by Django 5.2.15 on 2026-07-12 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0004_remove_channel_ai_fields'),
        ('conversations', '0004_conversationread'),
        ('identity', '0006_alter_employeeprofile_totp_secret'),
        ('integrations', '0002_integration_channel_integration_poll_marker'),
        ('products', '0008_remove_product_knowledge_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('LOCAL', 'Local'), ('STAGING', 'Staging'), ('PRODUCTION', 'Production')], default='PRODUCTION', max_length=16)),
                ('source_type', models.CharField(choices=[('PRODUCT_API', 'Product Sales API'), ('MANUAL', 'Ручная фиксация'), ('LEGACY_IMPORT', 'Импорт legacy')], max_length=16)),
                ('external_sale_id', models.CharField(blank=True, max_length=190)),
                ('external_customer_id', models.CharField(blank=True, max_length=190)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Подтверждена'), ('PARTIALLY_REFUNDED', 'Частичный возврат'), ('REFUNDED', 'Возврат'), ('CANCELLED', 'Отменена')], default='CONFIRMED', max_length=24)),
                ('amount_minor', models.PositiveBigIntegerField(default=0)),
                ('refunded_amount_minor', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('attribution_method', models.CharField(choices=[('ATTRIBUTION_TOKEN', 'Attribution token'), ('EXTERNAL_IDENTITY', 'External identity'), ('CONTACT_MATCH', 'Совпадение контакта'), ('MANUAL', 'Ручная привязка'), ('NONE', 'Без атрибуции')], default='NONE', max_length=24)),
                ('attributed_actor_type', models.CharField(blank=True, choices=[('AI_AGENT', 'AI-агент'), ('OPERATOR', 'Оператор'), ('OWNER', 'Владелец')], max_length=16)),
                ('attributed_actor_id', models.CharField(blank=True, max_length=64)),
                ('line_items_snapshot', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='conversations.contact')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='conversations.conversation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='identity.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='products.product')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('LOCAL', 'Local'), ('STAGING', 'Staging'), ('PRODUCTION', 'Production')], default='PRODUCTION', max_length=16)),
                ('source_type', models.CharField(choices=[('PRODUCT_API', 'Product Sales API'), ('MANUAL', 'Ручная фиксация'), ('LEGACY_IMPORT', 'Импорт legacy')], max_length=16)),
                ('external_event_id', models.CharField(blank=True, max_length=190)),
                ('event_type', models.CharField(choices=[('sale.confirmed', 'Подтверждение'), ('sale.corrected', 'Исправление'), ('sale.cancelled', 'Отмена'), ('sale.partially_refunded', 'Частичный возврат'), ('sale.refunded', 'Возврат'), ('sale.legacy_imported', 'Импорт legacy')], max_length=32)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('occurred_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('processing_status', models.CharField(choices=[('RECEIVED', 'Принято'), ('APPLIED', 'Применено'), ('REJECTED', 'Отклонено'), ('RETRYABLE', 'Повтор возможен')], default='RECEIVED', max_length=16)),
                ('processing_error', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_events', to='identity.organization')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='sales.sale')),
            ],
            options={
                'ordering': ['received_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='last_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.saleevent'),
        ),
        migrations.CreateModel(
            name='SalesSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64)),
                ('type', models.CharField(choices=[('PRODUCT_API', 'Product Sales API')], default='PRODUCT_API', max_length=32)),
                ('environment', models.CharField(choices=[('LOCAL', 'Local'), ('STAGING', 'Staging'), ('PRODUCTION', 'Production')], default='PRODUCTION', max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Активен'), ('READ_ONLY', 'Только чтение'), ('DISABLED', 'Отключён')], default='ACTIVE', max_length=16)),
                ('credential_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('credential_hint', models.CharField(blank=True, max_length=32)),
                ('allowed_schema_versions', models.JSONField(blank=True, default=list)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_sources', to='identity.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_sources', to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='saleevent',
            name='sales_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='sales.salessource'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sales_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.salessource'),
        ),
        migrations.CreateModel(
            name='AttributionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('actor_type', models.CharField(choices=[('AI_AGENT', 'AI-агент'), ('OPERATOR', 'Оператор'), ('OWNER', 'Владелец')], max_length=16)),
                ('actor_id', models.CharField(blank=True, max_length=64)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attribution_tokens', to='channels.channel')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribution_tokens', to='integrations.integration')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribution_tokens', to='conversations.contact')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribution_tokens', to='conversations.conversation')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribution_tokens', to='products.offer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribution_tokens', to='identity.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribution_tokens', to='products.product')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'expires_at'], name='sales_attri_organiz_f20532_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExternalCustomerIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('LOCAL', 'Local'), ('STAGING', 'Staging'), ('PRODUCTION', 'Production')], default='PRODUCTION', max_length=16)),
                ('external_customer_id', models.CharField(max_length=190)),
                ('verification_method', models.CharField(blank=True, max_length=32)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_customer_identities', to='conversations.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_customer_identities', to='identity.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_customer_identities', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'External customer identities',
                'constraints': [models.UniqueConstraint(fields=('product', 'environment', 'external_customer_id'), name='uniq_external_identity_product_env_customer')],
            },
        ),
        migrations.AddConstraint(
            model_name='salessource',
            constraint=models.UniqueConstraint(fields=('organization', 'product', 'code'), name='uniq_sales_source_org_product_code'),
        ),
        migrations.AddIndex(
            model_name='saleevent',
            index=models.Index(fields=['sale', 'occurred_at'], name='sales_salee_sale_id_f581d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='saleevent',
            constraint=models.UniqueConstraint(condition=models.Q(('sales_source__isnull', False), models.Q(('external_event_id', ''), _negated=True)), fields=('sales_source', 'external_event_id'), name='uniq_sale_event_source_external'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', 'status'], name='sales_sale_organiz_d17eae_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', 'environment', 'occurred_at'], name='sales_sale_organiz_a6807e_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('sales_source__isnull', False), models.Q(('external_sale_id', ''), _negated=True)), fields=('sales_source', 'external_sale_id'), name='uniq_sale_source_external'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gte', 0)), name='sale_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_amount_minor__gte', 0), ('refunded_amount_minor__lte', models.F('amount_minor'))), name='sale_refund_within_amount'),
        ),
    ]
