# Generated by Django 5.2.16 on 2026-07-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributiontoken',
            name='actor_type',
            field=models.CharField(choices=[('AI_AGENT', 'AI-агент'), ('EMPLOYEE', 'Сотрудник'), ('OPERATOR', 'Оператор'), ('OWNER', 'Владелец')], max_length=16),
        ),
        migrations.AlterField(
            model_name='sale',
            name='attributed_actor_type',
            field=models.CharField(blank=True, choices=[('AI_AGENT', 'AI-агент'), ('EMPLOYEE', 'Сотрудник'), ('OPERATOR', 'Оператор'), ('OWNER', 'Владелец')], max_length=16),
        ),
    ]
