# Generated by Django 5.2.15 on 2026-09-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_integration_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='provider',
            field=models.CharField(choices=[('OPENROUTER', 'OpenRouter'), ('CUSTOM', 'Custom (OpenAI-compatible)'), ('DEMO', 'Демо-провайдер (без ключа)'), ('MAX', 'MAX'), ('TELEGRAM', 'Telegram'), ('WEB', 'Web-виджет'), ('EMAIL', 'Email (IMAP/SMTP)')], max_length=16),
        ),
    ]
