# Generated by Django 5.2.16 on 2026-07-12 22:14

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_enforce_position_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_profiles', to='identity.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AccessProfileCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability_code', models.CharField(max_length=80)),
                ('access_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_links', to='identity.accessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAccessAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('ORGANIZATION', 'Organization'), ('DEPARTMENT', 'Department')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('access_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='identity.accessprofile')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_assignments_created', to='identity.employeeprofile')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_assignments', to='identity.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_assignments', to='identity.employeeprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='accessprofile',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('organization'), name='uniq_access_profile_org_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='accessprofilecapability',
            constraint=models.UniqueConstraint(fields=('access_profile', 'capability_code'), name='uniq_access_profile_capability'),
        ),
        migrations.AddConstraint(
            model_name='employeeaccessassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('department__isnull', True), ('scope_type', 'ORGANIZATION')), models.Q(('department__isnull', False), ('scope_type', 'DEPARTMENT')), _connector='OR'), name='access_assignment_scope_department'),
        ),
        migrations.AddConstraint(
            model_name='employeeaccessassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True), ('scope_type', 'ORGANIZATION')), fields=('employee', 'access_profile'), name='uniq_active_org_access_assignment'),
        ),
        migrations.AddConstraint(
            model_name='employeeaccessassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True), ('scope_type', 'DEPARTMENT')), fields=('employee', 'access_profile', 'department'), name='uniq_active_dept_access_assignment'),
        ),
    ]
