# Generated by Django 5.2.16 on 2026-07-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0010_backfill_employee_access'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='accessprofilecapability',
            constraint=models.CheckConstraint(condition=models.Q(('capability_code__in', ['company.view', 'company.manage', 'departments.view', 'departments.manage', 'employees.view', 'employees.manage', 'products.view', 'products.manage', 'ai.view', 'ai.manage', 'ai.publish', 'integrations.view', 'integrations.manage', 'secrets.manage', 'settings.view', 'settings.manage', 'audit.view', 'conversations.view', 'conversations.operate', 'conversations.call', 'customers.view', 'customers.manage', 'sales.view', 'sales.operate', 'sales.correct', 'sales_sources.manage', 'support.view', 'support.operate', 'notifications.manage'])), name='access_profile_capability_registry'),
        ),
    ]
