# Generated by Django 5.2.16 on 2026-07-15 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0013_accessprofilecapability_organization_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM identity_employeeaccessassignment assignment
                        JOIN identity_employeeprofile employee ON employee.id = assignment.employee_id
                        JOIN identity_accessprofile profile ON profile.id = assignment.access_profile_id
                        JOIN identity_employeeprofile assigner ON assigner.id = assignment.assigned_by_id
                        LEFT JOIN identity_department department ON department.id = assignment.department_id
                        WHERE employee.organization_id <> profile.organization_id
                           OR employee.organization_id <> assigner.organization_id
                           OR (department.id IS NOT NULL AND employee.organization_id <> department.organization_id)
                    ) THEN
                        RAISE EXCEPTION 'C04 preflight: cross-tenant access assignment exists';
                    END IF;
                END $$;

                UPDATE identity_accessprofilecapability capability
                SET organization_id = profile.organization_id
                FROM identity_accessprofile profile
                WHERE capability.access_profile_id = profile.id;

                UPDATE identity_employeeaccessassignment assignment
                SET organization_id = employee.organization_id
                FROM identity_employeeprofile employee
                WHERE assignment.employee_id = employee.id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='accessprofilecapability',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
        migrations.AlterField(
            model_name='employeeaccessassignment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
    ]
