# Generated by Django 5.2.15 on 2026-09-03 22:23

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models

# При откате Django пересоздаёт снесённые таблицы «голыми» — без ownership и
# грантов, которые исходно раздавала tenancy/0003 (она при откате не
# переприменяется). SECURITY DEFINER-триггеры (enforce_tenant_fk) тогда не могут
# читать identity_department и migration-тесты падают на старых состояниях.
# Первый operation ниже — noop вперёд; его reverse выполняется ПОСЛЕДНИМ при
# откате (операции разворачиваются в обратном порядке), когда таблицы уже
# пересозданы, и возвращает им владельца и гранты. RLS на старых состояниях
# тестами не используется, поэтому политики не восстанавливаем.
_RESTORE_GRANTS_SQL = "\n".join(
    f"""
ALTER TABLE {table} OWNER TO chatballs_schema;
GRANT ALL ON {table} TO chatballs_schema;
GRANT SELECT, INSERT, UPDATE, DELETE ON {table} TO chatballs_runtime_app;
"""
    for table in (
        "identity_department",
        "identity_accessprofile",
        "identity_accessprofilecapability",
        "identity_employeeaccessassignment",
    )
)


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0014_remove_knowledgedepartment_department_and_more'),
        ('channels', '0006_remove_channel_department'),
        ('identity', '0019_drop_sales_capabilities'),
        ('notifications', '0008_remove_notification_department'),
        ('products', '0012_delete_productdepartment'),
        ('support_portals', '0008_remove_supportportal_department'),
    ]

    operations = [
        migrations.RunSQL(migrations.RunSQL.noop, _RESTORE_GRANTS_SQL),
        migrations.CreateModel(
            name='EmployeeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        # Снимаем constraint'ы удаляемых моделей до удаления их полей: иначе
        # state хранит constraint на несуществующее поле и обратная миграция
        # (reverse DeleteModel в migration-тестах) падает при create_model.
        migrations.RemoveConstraint(
            model_name='accessprofile',
            name='uniq_access_profile_org_name_ci',
        ),
        migrations.RemoveConstraint(
            model_name='accessprofilecapability',
            name='uniq_access_profile_capability',
        ),
        migrations.RemoveConstraint(
            model_name='department',
            name='uniq_department_org_code',
        ),
        migrations.RemoveConstraint(
            model_name='employeeaccessassignment',
            name='access_assignment_scope_department',
        ),
        migrations.RemoveConstraint(
            model_name='employeeaccessassignment',
            name='uniq_active_org_access_assignment',
        ),
        migrations.RemoveConstraint(
            model_name='employeeaccessassignment',
            name='uniq_active_dept_access_assignment',
        ),
        migrations.RemoveField(
            model_name='accessprofile',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='accessprofilecapability',
            name='access_profile',
        ),
        migrations.RemoveField(
            model_name='employeeaccessassignment',
            name='access_profile',
        ),
        migrations.RemoveField(
            model_name='accessprofilecapability',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='department',
            name='organization',
        ),
        # Сначала снимаем constraint, зависящий от primary_department: дроп
        # колонки удалил бы его каскадно и RemoveConstraint ниже упал бы.
        migrations.RemoveConstraint(
            model_name='organizationmembership',
            name='owner_is_company_level',
        ),
        migrations.RemoveField(
            model_name='organizationmembership',
            name='primary_department',
        ),
        migrations.RemoveField(
            model_name='employeeaccessassignment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employeeaccessassignment',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='employeeaccessassignment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeaccessassignment',
            name='organization',
        ),
        migrations.AddField(
            model_name='employeegroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_groups', to='identity.organization'),
        ),
        migrations.AddField(
            model_name='employeegroupmember',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_links', to='identity.organizationmembership'),
        ),
        migrations.AddField(
            model_name='employeegroupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_links', to='identity.employeegroup'),
        ),
        migrations.AddField(
            model_name='employeegroupmember',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
        migrations.DeleteModel(
            name='AccessProfile',
        ),
        migrations.DeleteModel(
            name='AccessProfileCapability',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='EmployeeAccessAssignment',
        ),
        migrations.AddConstraint(
            model_name='employeegroup',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('organization'), name='uniq_employee_group_org_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='employeegroupmember',
            constraint=models.UniqueConstraint(fields=('group', 'employee'), name='uniq_employee_group_member'),
        ),
    ]
