# Generated by Django 5.2.15 on 2026-09-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0020_employeegroup_employeegroupmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanuser',
            name='ui_accent',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='humanuser',
            name='ui_theme',
            field=models.CharField(choices=[('LIGHT', 'Светлая'), ('DARK', 'Тёмная'), ('SYSTEM', 'Как в системе')], default='SYSTEM', max_length=8),
        ),
    ]
