# Generated by Django 5.2.15 on 2026-09-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0026_humanuser_password_changed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceSettings',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('public_host', models.CharField(blank=True, default='', max_length=253)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки установки',
            },
        ),
    ]
