# Generated by Django 5.2.15 on 2026-09-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0027_instance_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancesettings',
            name='public_scheme',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
