# Generated by Django 5.2.15 on 2026-09-07 01:55

import chatballs.identity.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0028_instance_public_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancesettings',
            name='email_from',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='instancesettings',
            name='email_host',
            field=models.CharField(blank=True, default='', max_length=253),
        ),
        migrations.AddField(
            model_name='instancesettings',
            name='email_password',
            field=chatballs.identity.crypto.EncryptedCharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='instancesettings',
            name='email_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='instancesettings',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instancesettings',
            name='email_user',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
