# Generated by Django 5.2.15 on 2026-09-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0029_instance_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancesettings',
            name='turn_ttl_seconds',
            field=models.PositiveIntegerField(default=3600),
        ),
        migrations.AddField(
            model_name='instancesettings',
            name='turn_urls',
            field=models.TextField(blank=True, default=''),
        ),
    ]
