# Generated by Django 5.2.15 on 2026-09-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0031_totp_last_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='tax_regime',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='vat_mode',
        ),
    ]
