# Generated by Django 5.2.17 on 2026-09-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0034_encrypted_column_widths'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanuser',
            name='ui_language',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='instancesettings',
            name='default_language',
            field=models.CharField(blank=True, default='ru', max_length=5),
        ),
        migrations.AddField(
            model_name='organization',
            name='language',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
