# Generated by Django 5.2.15 on 2026-06-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='system_prompt',
            field=models.TextField(blank=True),
        ),
    ]
