# Generated by Django 5.2.15 on 2026-09-03 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_remove_channel_department'),
        ('identity', '0020_employeegroup_employeegroupmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='identity.employeegroup'),
        ),
    ]
