# Generated by Django 5.2.15 on 2026-06-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_price_uniq_price_offer_version_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='price',
            name='price_amount_positive',
        ),
        migrations.AlterField(
            model_name='offer',
            name='fiscal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gte', 0)), name='price_amount_non_negative'),
        ),
    ]
