# Generated by Django 5.2.15 on 2026-07-08 21:29

import chatballs.identity.crypto
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_ingest_token_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='support_token_secret',
            field=chatballs.identity.crypto.EncryptedCharField(blank=True, max_length=512),
        ),
    ]
