# Generated by Django 5.2.15 on 2026-06-27 22:30

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0002_channel_system_prompt'),
        ('identity', '0006_alter_employeeprofile_totp_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('model', models.CharField(default='anthropic/claude-sonnet-4.6', max_length=128)),
                ('model_params', models.JSONField(blank=True, default=dict)),
                ('allowed_tools', models.JSONField(blank=True, default=list)),
                ('limits', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_agent', to='channels.channel')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelAIRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Опубликован'), ('ARCHIVED', 'Архив')], default='DRAFT', max_length=16)),
                ('model', models.CharField(max_length=128)),
                ('model_params', models.JSONField(blank=True, default=dict)),
                ('allowed_tools', models.JSONField(blank=True, default=list)),
                ('limits', models.JSONField(blank=True, default=dict)),
                ('retrieval_index_version', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_releases', to='channels.channel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['channel_id', '-version'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('GLOBAL', 'Глобальное'), ('PRODUCT', 'Продуктовое')], default='GLOBAL', max_length=16)),
                ('code', models.SlugField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('OVERVIEW', 'Обзор продукта'), ('AUDIENCE', 'Целевая аудитория'), ('COMMERCIAL', 'Коммерческая модель'), ('TECHNICAL', 'Техническая информация'), ('FAQ', 'FAQ'), ('OBJECTIONS', 'Возражения'), ('LIMITATIONS', 'Ограничения')], max_length=32)),
                ('inclusion_mode', models.CharField(choices=[('MANDATORY', 'Обязательное включение'), ('RETRIEVAL', 'Доступно для retrieval')], default='RETRIEVAL', max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='identity.organization')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeDocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Опубликован'), ('ARCHIVED', 'Архив')], default='DRAFT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ai.knowledgedocument')),
            ],
            options={
                'ordering': ['-version'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='ai.knowledgedocumentversion')),
            ],
            options={
                'ordering': ['version_id', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='LlmInvocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=64)),
                ('operation', models.CharField(max_length=16)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cost_micros', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('SUCCESS', 'Успех'), ('ERROR', 'Ошибка'), ('BLOCKED', 'Заблокировано лимитом')], default='SUCCESS', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('used_fragment_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_invocations', to='channels.channel')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invocations', to='ai.channelairelease')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('GLOBAL', 'Глобальное'), ('PRODUCT', 'Продуктовое')], default='GLOBAL', max_length=16)),
                ('code', models.SlugField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('SYSTEM', 'Системный промпт'), ('QUALIFICATION', 'Квалификация'), ('SALES_BEHAVIOR', 'Поведение в продаже'), ('OPERATOR_HANDOFF', 'Передача оператору')], max_length=32)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='identity.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PromptDocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Опубликован'), ('ARCHIVED', 'Архив')], default='DRAFT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ai.promptdocument')),
            ],
            options={
                'ordering': ['-version'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReleaseKnowledgeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ai.knowledgedocumentversion')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_versions', to='ai.channelairelease')),
            ],
        ),
        migrations.CreateModel(
            name='ReleasePromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ai.promptdocumentversion')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_versions', to='ai.channelairelease')),
            ],
        ),
        migrations.AddConstraint(
            model_name='channelairelease',
            constraint=models.UniqueConstraint(fields=('channel', 'version'), name='uniq_release_channel_version'),
        ),
        migrations.AddConstraint(
            model_name='channelairelease',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PUBLISHED')), fields=('channel',), name='uniq_active_release_per_channel'),
        ),
        migrations.AddConstraint(
            model_name='knowledgedocumentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='uniq_knowledge_version'),
        ),
        migrations.AddConstraint(
            model_name='knowledgefragment',
            constraint=models.UniqueConstraint(fields=('version', 'chunk_index'), name='uniq_fragment_version_chunk'),
        ),
        migrations.AddIndex(
            model_name='llminvocation',
            index=models.Index(fields=['channel', 'created_at'], name='ai_llminvoc_channel_dbf239_idx'),
        ),
        migrations.AddConstraint(
            model_name='promptdocumentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='uniq_prompt_version'),
        ),
        migrations.AddConstraint(
            model_name='releaseknowledgeversion',
            constraint=models.UniqueConstraint(fields=('release', 'knowledge_version'), name='uniq_release_knowledge_version'),
        ),
        migrations.AddConstraint(
            model_name='releasepromptversion',
            constraint=models.UniqueConstraint(fields=('release', 'prompt_version'), name='uniq_release_prompt_version'),
        ),
    ]
