# Generated by Django 5.2.16 on 2026-07-15 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_aiagent_organization_and_more'),
        ('identity', '0014_alter_accessprofilecapability_organization_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM ai_llminvocation invocation
                        LEFT JOIN channels_channel channel ON channel.id = invocation.channel_id
                        WHERE channel.id IS NULL
                    ) THEN
                        RAISE EXCEPTION 'C04 preflight: ambiguous LLM invocation exists';
                    END IF;
                END $$;

                UPDATE ai_aiagent agent
                SET organization_id = channel.organization_id
                FROM channels_channel channel
                WHERE agent.channel_id = channel.id;

                UPDATE ai_knowledgeattachment attachment
                SET organization_id = knowledge.organization_id
                FROM ai_knowledge knowledge
                WHERE attachment.knowledge_id = knowledge.id;

                UPDATE ai_knowledgefragment fragment
                SET organization_id = knowledge.organization_id
                FROM ai_knowledge knowledge
                WHERE fragment.knowledge_id = knowledge.id;

                UPDATE ai_llminvocation invocation
                SET organization_id = channel.organization_id
                FROM channels_channel channel
                WHERE channel.id = invocation.channel_id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='aiagent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
        migrations.AlterField(
            model_name='knowledgeattachment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
        migrations.AlterField(
            model_name='knowledgefragment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
        migrations.AlterField(
            model_name='llminvocation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
    ]
