# Generated by Django 5.2.16 on 2026-07-15 02:40

from django.db import migrations, models


def backfill_agent_status(apps, schema_editor):
    AIAgent = apps.get_model("ai", "AIAgent")
    AIAgent.objects.filter(is_active=True).update(status="ACTIVE")
    AIAgent.objects.filter(is_active=False).update(status="DISABLED")


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_alter_aiagent_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='lifecycle_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='status',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.RunPython(backfill_agent_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='aiagent',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('DISABLED', 'Disabled'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16),
        ),
        migrations.RemoveField(
            model_name='aiagent',
            name='is_active',
        ),
    ]
