# Generated by Django 5.2.15 on 2026-08-01 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0012_agent_provider_integration'),
        ('identity', '0018_organization_branding_db_defaults'),
        ('support_portals', '0006_support_portal_widget_channel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgefragment',
            options={'ordering': ['knowledge_id', 'portal_article_id', 'chunk_index']},
        ),
        migrations.AddField(
            model_name='aiagent',
            name='portal_articles',
            field=models.ManyToManyField(blank=True, related_name='agents', to='support_portals.portalarticle'),
        ),
        migrations.AddField(
            model_name='knowledgefragment',
            name='portal_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='support_portals.portalarticle'),
        ),
        migrations.AlterField(
            model_name='knowledgefragment',
            name='knowledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='ai.knowledge'),
        ),
        migrations.AddConstraint(
            model_name='knowledgefragment',
            constraint=models.UniqueConstraint(fields=('portal_article', 'chunk_index'), name='uniq_fragment_article_chunk'),
        ),
        migrations.AddConstraint(
            model_name='knowledgefragment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('knowledge__isnull', False), ('portal_article__isnull', True)), models.Q(('knowledge__isnull', True), ('portal_article__isnull', False)), _connector='OR'), name='fragment_single_source'),
        ),
    ]
