# Generated by Django 5.2.16 on 2026-07-15 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0013_accessprofilecapability_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationStorageUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes_used', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='storage_usage', to='identity.organization')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('bytes_used__gte', 0)), name='storage_usage_bytes_non_negative')],
            },
        ),
    ]
