# Generated by Django 5.2.15 on 2026-06-28 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0002_channel_system_prompt'),
        ('identity', '0006_alter_employeeprofile_totp_secret'),
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='identity.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_chat_id', models.CharField(blank=True, max_length=128)),
                ('lifecycle', models.CharField(choices=[('OPEN', 'Открыт'), ('CLOSED', 'Закрыт'), ('SPAM', 'Спам')], default='OPEN', max_length=16)),
                ('control_mode', models.CharField(choices=[('AI', 'AI'), ('HUMAN', 'Оператор'), ('PAUSED', 'Пауза')], default='AI', max_length=16)),
                ('expected_responder', models.CharField(choices=[('CUSTOMER', 'Клиент'), ('AI', 'AI'), ('OPERATOR', 'Оператор'), ('NOBODY', 'Никто')], default='AI', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assigned_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='channels.channel')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='integrations.integration')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='conversations.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='identity.organization')),
                ('previous_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conversations.conversation')),
            ],
            options={
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_type', models.CharField(choices=[('CONTACT', 'Клиент'), ('AI', 'AI'), ('OPERATOR', 'Оператор'), ('SYSTEM', 'Система')], max_length=16)),
                ('text', models.TextField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_user_id', models.CharField(max_length=128)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identities', to='integrations.integration')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='conversations.contact')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('connection', 'external_user_id'), name='uniq_identity_connection_user')],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['channel', 'lifecycle'], name='conversatio_channel_a937dc_idx'),
        ),
    ]
