# Generated by Django 5.2.15 on 2026-07-08 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_channel_allow_anonymous_sessions_and_more'),
        ('conversations', '0001_initial'),
        ('identity', '0006_alter_employeeprofile_totp_secret'),
        ('integrations', '0002_integration_channel_integration_poll_marker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='conversations.contact'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(('contact__isnull', False)), name='conversation_requires_contact'),
        ),
    ]
