# Generated by Django 5.2.15 on 2026-09-04 16:41

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0010_conversation_group'),
        ('identity', '0020_employeegroup_employeegroupmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'Высокий'), ('MEDIUM', 'Средний'), ('LOW', 'Низкий'), ('NONE', 'Не задан')], default='NONE', max_length=8),
        ),
        migrations.CreateModel(
            name='ConversationLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_labels', to='identity.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='conversations', to='conversations.conversationlabel'),
        ),
        migrations.CreateModel(
            name='ReplyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reply_templates', to='identity.organization')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddConstraint(
            model_name='conversationlabel',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('organization'), name='uniq_conversation_label_org_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='replytemplate',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('organization'), name='uniq_reply_template_org_title_ci'),
        ),
    ]
