# Generated by Django 5.2.15 on 2026-09-04 22:30

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0012_message_audio_message_audio_content_type_and_more'),
        ('identity', '0021_humanuser_ui_accent_humanuser_ui_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('text', config='russian'), name='conv_message_text_fts'),
        ),
    ]
