# Generated by Django 5.2.15 on 2026-06-19 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_move_product_state'),
        ('products', '0001_move_product_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('fulfillment_type', models.CharField(choices=[('SAAS_ACCESS', 'SaaS-доступ'), ('BOX_LICENSE', 'Коробочная лицензия'), ('SUPPORT_EXTENSION', 'Продление поддержки')], max_length=32)),
                ('payment_type', models.CharField(choices=[('ONE_TIME', 'Разовая оплата'), ('SUBSCRIPTION', 'Подписка')], max_length=32)),
                ('access_schema', models.JSONField(blank=True, default=dict)),
                ('fiscal_name', models.CharField(max_length=255)),
                ('fiscal_attributes', models.JSONField(blank=True, default=dict)),
                ('subscription_rules', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('ai_offerable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_box_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_extensions', to='products.offer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('billing_period', models.CharField(choices=[('ONE_TIME', 'Разово'), ('MONTH', 'Месяц'), ('YEAR', 'Год')], max_length=16)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='products.offer')),
            ],
            options={
                'ordering': ['offer_id', 'billing_period', '-version'],
            },
        ),
        migrations.CreateModel(
            name='MarketplacePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_code', models.SlugField(max_length=64)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Опубликовано'), ('DISABLED', 'Отключено')], default='DRAFT', max_length=16)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_publications', to='products.price')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_links', to='identity.department')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_links', to='products.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(fields=('product', 'code'), name='uniq_offer_product_code'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fulfillment_type', 'SUPPORT_EXTENSION'), ('primary_box_offer__isnull', False)), models.Q(('fulfillment_type', 'SUPPORT_EXTENSION'), _negated=True), _connector='OR'), name='support_offer_requires_primary_box'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(fields=('offer', 'version'), name='uniq_price_offer_version'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('offer', 'currency', 'billing_period'), name='uniq_active_price_offer_currency_period'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='price_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='marketplacepublication',
            constraint=models.UniqueConstraint(fields=('marketplace_code', 'price'), name='uniq_marketplace_price_publication'),
        ),
        migrations.AddConstraint(
            model_name='productdepartment',
            constraint=models.UniqueConstraint(fields=('product', 'department'), name='uniq_product_department'),
        ),
    ]
