# Generated by Django 5.2.15 on 2026-06-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_assign_existing_products_to_sales'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='price',
            name='uniq_price_offer_version',
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(fields=('offer', 'currency', 'billing_period', 'version'), name='uniq_price_offer_period_version'),
        ),
    ]
