# Generated by Django 5.2.15 on 2026-06-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_price_price_amount_positive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingest_token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
