# Generated by Django 5.2.16 on 2026-07-15 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0013_accessprofilecapability_organization_and_more'),
        ('products', '0008_remove_product_knowledge_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacepublication',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
        migrations.AddField(
            model_name='offer',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
        migrations.AddField(
            model_name='price',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
        migrations.AddField(
            model_name='productdepartment',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
    ]
