# Generated by Django 5.2.16 on 2026-07-15 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0014_alter_accessprofilecapability_organization_and_more'),
        ('products', '0009_marketplacepublication_organization_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM products_productdepartment link
                        JOIN identity_product product ON product.id = link.product_id
                        JOIN identity_department department ON department.id = link.department_id
                        WHERE product.organization_id <> department.organization_id
                    ) THEN
                        RAISE EXCEPTION 'C04 preflight: cross-tenant product department exists';
                    END IF;
                    IF EXISTS (
                        SELECT 1
                        FROM products_offer offer
                        JOIN products_offer primary_offer ON primary_offer.id = offer.primary_box_offer_id
                        JOIN identity_product product ON product.id = offer.product_id
                        JOIN identity_product primary_product ON primary_product.id = primary_offer.product_id
                        WHERE product.organization_id <> primary_product.organization_id
                    ) THEN
                        RAISE EXCEPTION 'C04 preflight: cross-tenant offer relation exists';
                    END IF;
                END $$;

                UPDATE products_offer offer
                SET organization_id = product.organization_id
                FROM identity_product product
                WHERE offer.product_id = product.id;

                UPDATE products_price price
                SET organization_id = product.organization_id
                FROM products_offer offer
                JOIN identity_product product ON product.id = offer.product_id
                WHERE price.offer_id = offer.id;

                UPDATE products_marketplacepublication publication
                SET organization_id = product.organization_id
                FROM products_price price
                JOIN products_offer offer ON offer.id = price.offer_id
                JOIN identity_product product ON product.id = offer.product_id
                WHERE publication.price_id = price.id;

                UPDATE products_productdepartment link
                SET organization_id = product.organization_id
                FROM identity_product product
                WHERE link.product_id = product.id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='marketplacepublication',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
        migrations.AlterField(
            model_name='price',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
        migrations.AlterField(
            model_name='productdepartment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
    ]
