import type { RouteKey } from "./types";

export const routes: Record<RouteKey, string> = {
  accessProfiles: "Профили доступа",
  administrationOrganization: "Организация",
  administrationSubscription: "Тариф и оплата",
  administrationAudit: "Аудит",
  command: "Обзор",
  departments: "Отделы",
  employeeDetail: "Сотрудники",
  employees: "Сотрудники",
  productDetail: "Продукты",
  products: "Продукты",
  profile: "Профиль",
  settings: "Настройки",
  salesClientDetail: "Контакт",
  salesClients: "Контакты",
  salesDialogs: "Диалоги",
  salesOrderDetail: "Продажа",
  salesOrders: "Продажи",
  salesOverview: "Обзор",
  supportOverview: "Обзор",
  supportDialogs: "Диалоги",
  supportPortals: "Порталы",
  supportPortalDetail: "Портал поддержки",
  aiAgents: "AI-агенты",
  aiAgentCreate: "Создание агента",
  aiAgentDetail: "Карточка агента",
  aiKnowledge: "Знания",
  aiKnowledgeCreate: "Создание знания",
  aiKnowledgeDetail: "Знание",
  aiUsage: "Использование AI",
  integrations: "Интеграции",
  channels: "Каналы",
  channelCreate: "Создание канала",
  channelDetail: "Карточка канала",
};
