import type { RouteKey } from "./types";

export const routes: Record<RouteKey, string> = {
  accessProfiles: "Профили доступа",
  command: "Обзор",
  departments: "Отделы",
  employeeDetail: "Сотрудники",
  employees: "Сотрудники",
  productDetail: "Продукты",
  products: "Продукты",
  profile: "Профиль",
  settings: "Настройки",
  salesClientDetail: "Контакт",
  salesClients: "Контакты",
  salesDialogs: "Диалоги",
  salesOrderDetail: "Продажа",
  salesOrders: "Продажи",
  salesOverview: "Обзор",
  supportOverview: "Обзор",
  supportDialogs: "Диалоги",
  aiAgents: "AI-агенты",
  aiAgentCreate: "Создание агента",
  aiAgentDetail: "Карточка агента",
  aiKnowledge: "Знания",
  aiKnowledgeDetail: "Знание",
  aiUsage: "Использование AI",
  integrations: "Интеграции",
};
