import type { RouteKey } from "./types";

export const routes: Record<RouteKey, string> = {
  command: "Командный центр",
  departments: "Отделы",
  employeeDetail: "Сотрудники",
  employees: "Сотрудники",
  productDetail: "Продукты",
  products: "Продукты",
  profile: "Профиль",
  salesClientDetail: "Клиент",
  salesClients: "Клиенты",
  salesDialogs: "Диалоги",
  salesOrderDetail: "Заказ",
  salesOrders: "Продажи",
  salesOverview: "Обзор",
  supportOverview: "Обзор",
  supportDialogs: "Диалоги",
  aiAgents: "AI-агенты",
  aiAgentCreate: "Создание агента",
  aiAgentDetail: "Карточка агента",
  aiRelease: "Версия продукта",
  aiTestChat: "Тестовый чат",
  aiUsage: "Использование AI",
  integrations: "Интеграции",
};
