# Generated by Django 5.2.16 on 2026-07-11 16:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0004_conversationread'),
        ('identity', '0006_alter_employeeprofile_totp_secret'),
        ('integrations', '0002_integration_channel_integration_poll_marker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('REQUESTED', 'Запрошен'), ('RINGING', 'Ожидание ответа'), ('ACCEPTED', 'Принят'), ('CONNECTING', 'Соединение'), ('ACTIVE', 'Активен'), ('DECLINED', 'Отклонён'), ('CANCELLED', 'Отменён'), ('MISSED', 'Пропущен'), ('ENDED', 'Завершён'), ('FAILED', 'Ошибка'), ('EXPIRED', 'Истёк')], db_index=True, default='REQUESTED', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ended_by', models.CharField(blank=True, choices=[('STAFF', 'Сотрудник'), ('CUSTOMER', 'Клиент'), ('SYSTEM', 'Система'), ('TIMEOUT', 'Таймаут')], max_length=16)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_sessions', to='conversations.conversation')),
                ('delivery_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivered_calls', to='integrations.integration')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_calls', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_sessions', to='identity.organization')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='CallParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('STAFF', 'Сотрудник'), ('CUSTOMER', 'Клиент')], max_length=16)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('last_connection_state', models.CharField(choices=[('PENDING', 'Ожидание'), ('CONNECTING', 'Соединение'), ('CONNECTED', 'Подключён'), ('RECONNECTING', 'Переподключение'), ('DISCONNECTED', 'Отключён'), ('FAILED', 'Ошибка')], default='PENDING', max_length=16)),
                ('connection_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='call_participations', to='conversations.connectionidentity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='call_participations', to=settings.AUTH_USER_MODEL)),
                ('call_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='calls.callsession')),
            ],
        ),
        migrations.CreateModel(
            name='CallInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Ожидает доставки'), ('SENT', 'Отправлено'), ('FAILED', 'Ошибка доставки')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection_identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_invites', to='conversations.connectionidentity')),
                ('call_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='calls.callsession')),
            ],
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['organization', 'status'], name='calls_calls_organiz_40d2ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='callsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('REQUESTED', 'RINGING', 'ACCEPTED', 'CONNECTING', 'ACTIVE'))), fields=('conversation',), name='uniq_unfinished_call_conversation'),
        ),
        migrations.AddConstraint(
            model_name='callsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('REQUESTED', 'RINGING', 'ACCEPTED', 'CONNECTING', 'ACTIVE'))), fields=('initiated_by',), name='uniq_unfinished_call_initiator'),
        ),
        migrations.AddConstraint(
            model_name='callparticipant',
            constraint=models.UniqueConstraint(fields=('call_session', 'side'), name='uniq_call_participant_side'),
        ),
        migrations.AddConstraint(
            model_name='callparticipant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('connection_identity__isnull', True), ('side', 'STAFF'), ('user__isnull', False)), models.Q(('connection_identity__isnull', False), ('side', 'CUSTOMER'), ('user__isnull', True)), _connector='OR'), name='call_participant_identity_matches_side'),
        ),
    ]
