# Generated by Django 5.2.16 on 2026-07-15 02:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0014_alter_accessprofilecapability_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntitlementDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('FREE', 'Бесплатный'), ('STARTUP', 'Стартап'), ('BUSINESS', 'Бизнес'), ('CORPORATION', 'Корпорация')], max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('saleable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='QuotaDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('unit', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='PlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField()),
                ('agent_unit_price_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('billing_period', models.CharField(choices=[('MONTH', 'Month')], default='MONTH', max_length=16)),
                ('fixed_ai_agent_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('transition_rules', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='subscriptions.plan')),
            ],
            options={
                'ordering': ['plan__code', 'version'],
            },
        ),
        migrations.CreateModel(
            name='EntitlementGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='subscriptions.entitlementdefinition')),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlement_grants', to='subscriptions.planversion')),
            ],
        ),
        migrations.CreateModel(
            name='QuotaGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('HARD', 'Hard'), ('SOFT', 'Soft'), ('RATE', 'Rate'), ('CONCURRENT', 'Concurrent'), ('UNLIMITED', 'Unlimited')], max_length=16)),
                ('limit_source', models.CharField(choices=[('FIXED', 'Fixed'), ('SUBSCRIPTION_AI_AGENT_QUANTITY', 'Subscription AI agent quantity')], default='FIXED', max_length=48)),
                ('limit_value', models.PositiveBigIntegerField(blank=True, null=True)),
                ('window_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='subscriptions.quotadefinition')),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_grants', to='subscriptions.planversion')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_agent_quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending payment'), ('ACTIVE', 'Active'), ('GRACE_PERIOD', 'Grace period'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], default='PENDING_PAYMENT', max_length=32)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('pending_ai_agent_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('suspension_reason', models.CharField(blank=True, max_length=64)),
                ('lifecycle_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='identity.organization')),
                ('pending_plan_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_subscriptions', to='subscriptions.planversion')),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.planversion')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('ENTITLEMENT', 'Entitlement'), ('QUOTA', 'Quota')], max_length=16)),
                ('operation', models.CharField(choices=[('ENABLE', 'Enable'), ('DISABLE', 'Disable'), ('SET', 'Set'), ('ADD', 'Add')], max_length=16)),
                ('value', models.BigIntegerField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_overrides_created', to=settings.AUTH_USER_MODEL)),
                ('entitlement_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overrides', to='subscriptions.entitlementdefinition')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_overrides', to='identity.organization')),
                ('quota_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overrides', to='subscriptions.quotadefinition')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsagePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_periods', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CONSUMPTION', 'Consumption'), ('RELEASE', 'Release'), ('ADJUSTMENT', 'Adjustment'), ('OPENING_BALANCE', 'Opening balance')], max_length=32)),
                ('quantity', models.BigIntegerField()),
                ('unit', models.CharField(max_length=32)),
                ('source', models.CharField(max_length=64)),
                ('aggregate_type', models.CharField(blank=True, max_length=64)),
                ('aggregate_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('rule_version', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correction_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='subscriptions.usageledgerentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('quota_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_ledger_entries', to='subscriptions.quotadefinition')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='subscriptions.usageperiod')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_value', models.PositiveBigIntegerField(default=0)),
                ('reserved_value', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('quota_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_counters', to='subscriptions.quotadefinition')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counters', to='subscriptions.usageperiod')),
            ],
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.UniqueConstraint(fields=('plan', 'version'), name='uniq_subscription_plan_version'),
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='subscription_plan_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='entitlementgrant',
            constraint=models.UniqueConstraint(fields=('plan_version', 'definition'), name='uniq_plan_version_entitlement'),
        ),
        migrations.AddConstraint(
            model_name='quotagrant',
            constraint=models.UniqueConstraint(fields=('plan_version', 'definition'), name='uniq_plan_version_quota'),
        ),
        migrations.AddConstraint(
            model_name='quotagrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('limit_value__isnull', True), ('mode', 'UNLIMITED')), models.Q(('limit_source', 'SUBSCRIPTION_AI_AGENT_QUANTITY'), ('limit_value__isnull', True)), models.Q(('limit_source', 'FIXED'), ('limit_value__isnull', False)), _connector='OR'), name='subscription_quota_limit_shape'),
        ),
        migrations.AddConstraint(
            model_name='quotagrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mode', 'RATE'), ('window_seconds__isnull', False)), models.Q(('mode', 'RATE'), _negated=True), _connector='OR'), name='subscription_rate_has_window'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('ai_agent_quantity__gt', 0)), name='subscription_ai_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('pending_ai_agent_quantity__isnull', True), ('pending_ai_agent_quantity__gt', 0), _connector='OR'), name='subscription_pending_ai_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('current_period_end__isnull', True), ('current_period_start__isnull', True)), models.Q(('current_period_end__isnull', False), ('current_period_start__isnull', False)), _connector='OR'), name='subscription_period_bounds_together'),
        ),
        migrations.AddIndex(
            model_name='subscriptionoverride',
            index=models.Index(fields=['organization', 'starts_at', 'ends_at'], name='subscriptio_organiz_a0d8a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionoverride',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entitlement_definition__isnull', False), ('operation__in', ['ENABLE', 'DISABLE']), ('quota_definition__isnull', True), ('target', 'ENTITLEMENT'), ('value__isnull', True)), models.Q(('entitlement_definition__isnull', True), ('operation__in', ['SET', 'ADD']), ('quota_definition__isnull', False), ('target', 'QUOTA'), ('value__isnull', False)), _connector='OR'), name='subscription_override_shape'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionoverride',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='subscription_override_valid_window'),
        ),
        migrations.AddConstraint(
            model_name='usageperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('subscription',), name='uniq_open_usage_period_per_subscription'),
        ),
        migrations.AddConstraint(
            model_name='usageperiod',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='subscription_usage_period_valid_bounds'),
        ),
        migrations.AddIndex(
            model_name='usageledgerentry',
            index=models.Index(fields=['organization', 'quota_definition', 'occurred_at'], name='subscriptio_organiz_ddfcd1_idx'),
        ),
        migrations.AddConstraint(
            model_name='usageledgerentry',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='uniq_usage_idempotency_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='usageledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='subscription_usage_quantity_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='usageledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'CONSUMPTION'), ('quantity__gt', 0)), models.Q(('kind', 'OPENING_BALANCE'), ('quantity__gt', 0)), models.Q(('kind', 'RELEASE'), ('quantity__lt', 0)), ('kind', 'ADJUSTMENT'), _connector='OR'), name='subscription_usage_entry_sign'),
        ),
        migrations.AddConstraint(
            model_name='usageledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'ADJUSTMENT'), ('correction_of__isnull', True), _connector='OR'), name='subscription_correction_link_only_for_adjustment'),
        ),
        migrations.AddConstraint(
            model_name='usagecounter',
            constraint=models.UniqueConstraint(fields=('period', 'quota_definition'), name='uniq_usage_counter_period_quota'),
        ),
    ]
