# Generated by Django 5.2.15 on 2026-07-15 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0015_organization_status'),
        ('subscriptions', '0003_rls_and_immutability'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=160)),
                ('aggregate_type', models.CharField(blank=True, default='', max_length=64)),
                ('aggregate_id', models.CharField(blank=True, default='', max_length=128)),
                ('source', models.CharField(max_length=128)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='subscriptions.usageperiod')),
                ('quota_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='subscriptions.quotadefinition')),
            ],
            options={
                'ordering': ['-acquired_at'],
                'indexes': [models.Index(fields=['organization', 'quota_definition'], name='subscriptio_organiz_31796f_idx'), models.Index(fields=['released_at', 'expires_at'], name='subscriptio_release_bcdf31_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='uniq_concurrent_reservation_idempotency')],
            },
        ),
        # RLS grants mirroring the other subscription tenant tables (0003): both
        # runtime roles see only matching tenant context; the schema role owns the
        # table. Without this, runtime could neither read nor write reservations.
        migrations.RunSQL(
            sql="""
                ALTER TABLE subscriptions_usagereservation OWNER TO custocrm_schema;
                ALTER TABLE subscriptions_usagereservation ENABLE ROW LEVEL SECURITY;
                ALTER TABLE subscriptions_usagereservation FORCE ROW LEVEL SECURITY;
                REVOKE ALL ON TABLE subscriptions_usagereservation FROM PUBLIC;
                GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE subscriptions_usagereservation
                    TO custocrm_runtime_app, custocrm_runtime_platform;
                GRANT ALL ON TABLE subscriptions_usagereservation TO custocrm_schema;
                DROP POLICY IF EXISTS custocrm_subscription_tenant ON subscriptions_usagereservation;
                CREATE POLICY custocrm_subscription_tenant ON subscriptions_usagereservation
                    FOR ALL TO custocrm_runtime_app, custocrm_runtime_platform
                    USING (organization_id = custocrm.current_organization_id())
                    WITH CHECK (organization_id = custocrm.current_organization_id());
                DROP POLICY IF EXISTS custocrm_schema_access ON subscriptions_usagereservation;
                CREATE POLICY custocrm_schema_access ON subscriptions_usagereservation
                    FOR ALL TO custocrm_schema USING (true) WITH CHECK (true);
            """,
            reverse_sql="DROP POLICY IF EXISTS custocrm_subscription_tenant ON subscriptions_usagereservation",
        ),
    ]
