# Generated by Django 5.2.15 on 2026-06-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='outboxevent',
            new_name='events_outb_status_9dabce_idx',
            old_name='events_outb_status_881ef5_idx',
        ),
        migrations.RenameIndex(
            model_name='outboxevent',
            new_name='events_outb_aggrega_11f4b9_idx',
            old_name='events_outb_aggrega_a2b510_idx',
        ),
    ]
