# Generated by Django 5.2.15 on 2026-07-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_channel_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='allow_anonymous_sessions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='allow_checkout_actions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='allow_sales_attribution',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='allow_self_reported_contact',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='requires_authenticated_product_identity',
            field=models.BooleanField(default=False),
        ),
    ]
