# Generated by Django 5.2.15 on 2026-09-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0007_channel_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='allow_checkout_actions',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='allow_sales_attribution',
        ),
    ]
