# Generated by Django 5.2.15 on 2026-06-29 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0002_channel_system_prompt'),
        ('conversations', '0001_initial'),
        ('identity', '0006_alter_employeeprofile_totp_secret'),
        ('products', '0005_remove_price_price_amount_positive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Ожидает оплаты'), ('PAID', 'Оплачен'), ('CANCELLED', 'Отменён'), ('REFUNDED', 'Возврат')], default='PENDING', max_length=16)),
                ('fulfillment_status', models.CharField(choices=[('NONE', 'Не требуется'), ('PENDING', 'В процессе'), ('DELIVERED', 'Исполнен'), ('FAILED', 'Ошибка')], default='NONE', max_length=16)),
                ('amount_minor', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='channels.channel')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='conversations.contact')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='conversations.conversation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='identity.organization')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount_minor', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.offer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.price')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', 'payment_status'], name='orders_orde_organiz_c2f725_idx'),
        ),
    ]
