# Generated by Django 5.2.15 on 2026-06-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_channel_system_prompt'),
        ('conversations', '0001_initial'),
        ('identity', '0006_alter_employeeprofile_totp_secret'),
        ('orders', '0001_initial'),
        ('products', '0006_product_ingest_token_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='external_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('organization', 'source', 'external_id'), name='uniq_order_org_source_external'),
        ),
    ]
