# Generated by Django 5.2.16 on 2026-07-15 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0013_accessprofilecapability_organization_and_more'),
        ('orders', '0002_order_external_id_order_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
    ]
