# Generated by Django 5.2.16 on 2026-07-15 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0014_alter_accessprofilecapability_organization_and_more'),
        ('orders', '0003_orderitem_organization'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM orders_orderitem item
                        JOIN orders_order customer_order ON customer_order.id = item.order_id
                        JOIN products_offer offer ON offer.id = item.offer_id
                        JOIN identity_product product ON product.id = offer.product_id
                        LEFT JOIN products_price price ON price.id = item.price_id
                        LEFT JOIN products_offer price_offer ON price_offer.id = price.offer_id
                        LEFT JOIN identity_product price_product ON price_product.id = price_offer.product_id
                        WHERE customer_order.organization_id <> product.organization_id
                           OR (price.id IS NOT NULL AND customer_order.organization_id <> price_product.organization_id)
                    ) THEN
                        RAISE EXCEPTION 'C04 preflight: cross-tenant order item exists';
                    END IF;
                END $$;

                UPDATE orders_orderitem item
                SET organization_id = customer_order.organization_id
                FROM orders_order customer_order
                WHERE item.order_id = customer_order.id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
    ]
