# Generated by Django 5.2.15 on 2026-07-10 21:27

import django.db.models.deletion
import hub_platform.notifications.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_integration_channel_integration_poll_marker'),
        ('notifications', '0002_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerBindingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_binding_codes', to='integrations.integration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_binding_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessengerBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_chat_id', models.CharField(max_length=128)),
                ('push_types', models.JSONField(blank=True, default=hub_platform.notifications.models.default_push_types)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_bindings', to='integrations.integration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_bindings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('integration', 'user'), name='uniq_binding_integration_user')],
            },
        ),
    ]
