# Generated by Django 5.2.16 on 2026-07-15 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0013_accessprofilecapability_organization_and_more'),
        ('notifications', '0004_notification_department_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengerbinding',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
        migrations.AddField(
            model_name='messengerbindingcode',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
        migrations.AddField(
            model_name='notificationread',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
    ]
