# Generated by Django 5.2.15 on 2026-09-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_remove_notification_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('DIALOG_WAITING', 'Диалог ждёт оператора'), ('DIALOG_NEW_MESSAGE', 'Новое сообщение в диалоге'), ('RELEASE_PUBLISHED', 'Опубликован релиз агента'), ('INTEGRATION_ERROR', 'Ошибка интеграции')], max_length=32),
        ),
    ]
