# Generated by Django 5.2.15 on 2026-06-28 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_channel_system_prompt'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connections', to='channels.channel'),
        ),
        migrations.AddField(
            model_name='integration',
            name='poll_marker',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
